/// Binary compatibility tests for yjs-dart.
///
/// These tests verify byte-for-byte compatibility with the JavaScript Yjs
/// implementation (v14.0.0-22). Reference byte sequences were generated by
/// `test/fixtures/generate_fixtures.js` using the vendored JS client with
/// deterministic clientID=1.
///
/// The tests verify three levels of compatibility:
///   1. **Encoding**: Dart produces identical state vectors and updates.
///   2. **Decoding**: Dart correctly applies JS-generated updates.
///   3. **Round-trip**: Encode → decode → re-encode produces same bytes.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:test/test.dart';
import 'package:yjs_dart/yjs_dart.dart';

/// Load fixtures from the JSON file generated by the JS Yjs client.
Map<String, dynamic> loadFixtures() {
  final file = File('test/fixtures/fixtures.json');
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

/// Convert a JSON list of ints to Uint8List.
Uint8List toBytes(List<dynamic> arr) =>
    Uint8List.fromList(arr.cast<int>());

void main() {
  late Map<String, dynamic> fixtures;

  setUpAll(() {
    fixtures = loadFixtures();
  });

  // ───────────────────────────────────────────────────────────────────────────
  // Level 1: Encoding — Dart produces identical bytes to JS
  // ───────────────────────────────────────────────────────────────────────────

  group('Encoding compatibility', () {
    test('empty doc', () {
      final f = fixtures['empty_doc'];
      final doc = Doc(DocOpts(clientID: 1));
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
    });

    test('array insert', () {
      final f = fixtures['array_insert'];
      final doc = Doc(DocOpts(clientID: 1));
      final arr = doc.getArray('arr');
      arr!.insert(0, ['a', 'b', 'c']);
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
      expect(arr!.toArray(), f['content']);
    });

    test('array push', () {
      final f = fixtures['array_push'];
      final doc = Doc(DocOpts(clientID: 1));
      final arr = doc.getArray('arr');
      arr!.insert(0, ['a', 'b', 'c']);
      final svBefore = encodeStateVector(doc);
      arr!.push([42]);
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
      // Incremental update (diff from svBefore)
      expect(encodeStateAsUpdate(doc, svBefore), toBytes(f['inc_update'] as List));
      expect(arr!.toArray(), f['content']);
    });

    test('array delete', () {
      final f = fixtures['array_delete'];
      final doc = Doc(DocOpts(clientID: 1));
      final arr = doc.getArray('arr');
      arr!.insert(0, ['a', 'b', 'c']);
      arr.delete(1, 1); // delete 'b'
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
      expect(arr!.toArray(), f['content']);
    });


    test('array insert at index (split)', () {
      final f = fixtures['array_insert_at'];
      final doc = Doc(DocOpts(clientID: 1));
      final arr = doc.getArray('arr');
      arr!.insert(0, ['a', 'b', 'c']);
      arr!.insert(1, ['x']); // insert 'x' after 'a'
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
      expect(arr!.toArray(), f['content']);
    });

    test('map attributes', () {
      final f = fixtures['map_attrs'];
      final doc = Doc(DocOpts(clientID: 1));
      final map = doc.getMap('map');
      map!.set('key1', 'hello');
      map!.set('key2', 123);
      map!.set('flag', true);
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
      expect(map!.toMap(), f['attrs']);
    });

    test('mixed array + map', () {
      final f = fixtures['mixed'];
      final doc = Doc(DocOpts(clientID: 1));
      final arr = doc.getArray('arr');
      final map = doc.getMap('map');
      arr!.insert(0, [1, 2, 3]);
      map!.set('name', 'test');
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
      expect(arr!.toArray(), f['arr_content']);
      expect(map!.toMap(), f['map_attrs']);
    });

    test('nested type', () {
      final f = fixtures['nested_type'];
      final doc = Doc(DocOpts(clientID: 1));
      final map = doc.getMap('map');
      final inner = YXmlFragment();
      map!.set('child', inner);
      (map!.get('child') as YXmlFragment).setAttribute('deep', 'value');
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
    });

    test('content types (string, int, bool, null, double)', () {
      final f = fixtures['content_types'];
      final doc = Doc(DocOpts(clientID: 1));
      final arr = doc.getArray('arr');
      arr!.insert(0, ['text', 42, true, false, null, 3.14]);
      expect(encodeStateVector(doc), toBytes(f['sv'] as List));
      expect(encodeStateAsUpdate(doc), toBytes(f['update'] as List));
      expect(arr!.toArray(), f['content']);
    });
  });

  // ───────────────────────────────────────────────────────────────────────────
  // Level 2: Decoding — Dart correctly applies JS-generated updates
  // ───────────────────────────────────────────────────────────────────────────

  group('Decoding compatibility', () {
// ...
    test('apply JS nested type update', () {
      final f = fixtures['nested_type'];
      final doc = Doc(DocOpts(clientID: 2));
      doc.getMap('map');
      applyUpdate(doc, toBytes(f['update'] as List));
      final map = doc.getMap('map');
      final child = map!.get('child');
      expect(child, isA<YXmlFragment>());
      expect((child as YXmlFragment).getAttribute('deep'), f['deep_value']);
    });
    test('apply JS array insert update', () {
      final f = fixtures['array_insert'];
      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, toBytes(f['update'] as List));
      final arr = doc.getArray('arr');
      expect(arr!.toArray(), f['content']);
    });

    test('apply JS array delete update', () {
      final f = fixtures['array_delete'];
      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, toBytes(f['update'] as List));
      final arr = doc.getArray('arr');
      expect(arr!.toArray(), f['content']);
    });

    test('apply JS array insert-at update', () {
      final f = fixtures['array_insert_at'];
      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, toBytes(f['update'] as List));
      final arr = doc.getArray('arr');
      expect(arr!.toArray(), f['content']);
    });

    test('apply JS map attributes update', () {
      final f = fixtures['map_attrs'];
      final doc = Doc(DocOpts(clientID: 2));
      doc.getMap('map');
      applyUpdate(doc, toBytes(f['update'] as List));
      final map = doc.getMap('map');
      expect(map!.toMap(), f['attrs']);
    });

    test('apply JS mixed update', () {
      final f = fixtures['mixed'];
      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      doc.getMap('map');
      applyUpdate(doc, toBytes(f['update'] as List));
      final arr = doc.getArray('arr');
      final map = doc.getMap('map');
      expect(arr!.toArray(), f['arr_content']);
      expect(map!.toMap(), f['map_attrs']);
    });


    test('apply JS content types update', () {
      final f = fixtures['content_types'];
      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, toBytes(f['update'] as List));
      final arr = doc.getArray('arr');
      expect(arr!.toArray(), f['content']);
    });

    test('apply JS incremental update', () {
      final f1 = fixtures['array_insert'];
      final f2 = fixtures['array_push'];

      // First apply base state
      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, toBytes(f1['update'] as List));

      // Then apply incremental update
      applyUpdate(doc, toBytes(f2['inc_update'] as List));
      final arr = doc.getArray('arr');
      expect(arr!.toArray(), f2['content']);
    });
  });

  // ───────────────────────────────────────────────────────────────────────────
  // Level 3: Cross-doc sync — Dart ↔ JS interop
  // ───────────────────────────────────────────────────────────────────────────

  group('Cross-doc sync compatibility', () {
    test('JS update applied to Dart doc produces same state vector', () {
      final f = fixtures['cross_doc_sync'];
      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, toBytes(f['doc1_update'] as List));

      // State vector should match (same content, different clientID context)
      expect(encodeStateVector(doc), toBytes(f['doc2_sv_after'] as List));
      final arr = doc.getArray('arr');
      expect(arr!.toArray(), f['doc2_content']);
    });

    test('bidirectional sync produces same content', () {
      final f = fixtures['bidirectional_sync'];
      final doc1 = Doc(DocOpts(clientID: 1));
      final doc2 = Doc(DocOpts(clientID: 2));

      final arr1 = doc1.getArray('arr');
      doc2.getArray('arr');

      arr1!.insert(0, ['from_doc1']);
      applyUpdate(doc2, encodeStateAsUpdate(doc1));

      final arr2 = doc2.getArray('arr');
      arr2!.push(['from_doc2']);

      final sv1 = encodeStateVector(doc1);
      applyUpdate(doc1, encodeStateAsUpdate(doc2, sv1));

      // Both docs should have same content as JS reference
      expect(arr1!.toArray(), f['doc1_content']);
      expect(arr2!.toArray(), f['doc2_content']);

      // State vectors should match
      expect(encodeStateVector(doc1), encodeStateVector(doc2));

      // State vectors should match JS reference
      expect(encodeStateVector(doc1), toBytes(f['doc1_sv'] as List));
      expect(encodeStateVector(doc2), toBytes(f['doc2_sv'] as List));
    });
  });

  // ───────────────────────────────────────────────────────────────────────────
  // Level 4: Round-trip — encode → decode → re-encode produces same bytes
  // ───────────────────────────────────────────────────────────────────────────

  group('Round-trip compatibility', () {
    test('array insert round-trip', () {
      final f = fixtures['array_insert'];
      final jsUpdate = toBytes(f['update'] as List);

      // Apply JS update to empty doc
      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, jsUpdate);

      // Re-encode and compare
      final dartUpdate = encodeStateAsUpdate(doc);
      expect(dartUpdate, jsUpdate);
    });

    test('array push round-trip', () {
      final f = fixtures['array_push'];
      final jsUpdate = toBytes(f['update'] as List);

      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, jsUpdate);

      final dartUpdate = encodeStateAsUpdate(doc);
      expect(dartUpdate, jsUpdate);
    });

    test('array delete round-trip', () {
      final f = fixtures['array_delete'];
      final jsUpdate = toBytes(f['update'] as List);

      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, jsUpdate);

      final dartUpdate = encodeStateAsUpdate(doc);
      expect(dartUpdate, jsUpdate);
    });

    test('map attrs round-trip', () {
      final f = fixtures['map_attrs'];
      final jsUpdate = toBytes(f['update'] as List);

      final doc = Doc(DocOpts(clientID: 2));
      doc.getMap('map');
      applyUpdate(doc, jsUpdate);

      final dartUpdate = encodeStateAsUpdate(doc);
      expect(dartUpdate, jsUpdate);
    });

    test('nested type round-trip', () {
      final f = fixtures['nested_type'];
      final jsUpdate = toBytes(f['update'] as List);

      final doc = Doc(DocOpts(clientID: 2));
      doc.getMap('map');
      applyUpdate(doc, jsUpdate);

      final dartUpdate = encodeStateAsUpdate(doc);
      expect(dartUpdate, jsUpdate);
    }, skip: 'readContentType returns stub — nested YType not reconstructed');

    test('content types round-trip', () {
      final f = fixtures['content_types'];
      final jsUpdate = toBytes(f['update'] as List);

      final doc = Doc(DocOpts(clientID: 2));
      doc.getArray('arr');
      applyUpdate(doc, jsUpdate);

      final dartUpdate = encodeStateAsUpdate(doc);
      expect(dartUpdate, jsUpdate);
    });

    test('empty doc round-trip', () {
      final f = fixtures['empty_doc'];
      final jsUpdate = toBytes(f['update'] as List);

      final doc = Doc(DocOpts(clientID: 1));

      final dartSv = encodeStateVector(doc);
      final dartUpdate = encodeStateAsUpdate(doc);
      expect(dartSv, toBytes(f['sv'] as List));
      expect(dartUpdate, jsUpdate);
    });
  });
}
